//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of parking spaces that are assigned for a particular purpose (e.g. short term parking) or for a particular class of vehicle or type of driver.
 * 
 * <p>Java class for AssignedParkingSpaces complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssignedParkingSpaces">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numberOfAssignedParkingSpaces" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger"/>
 *         &lt;element name="descriptionOfAssignedParkingSpaces" type="{http://datex2.eu/schema/2/2_0}DescriptionOfAssignedParkingSpaces"/>
 *         &lt;element name="assignedParkingSpacesExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssignedParkingSpaces", propOrder = {
    "numberOfAssignedParkingSpaces",
    "descriptionOfAssignedParkingSpaces",
    "assignedParkingSpacesExtension"
})
public class AssignedParkingSpaces {

    @XmlElement(required = true)
    protected BigInteger numberOfAssignedParkingSpaces;
    @XmlElement(required = true)
    protected DescriptionOfAssignedParkingSpaces descriptionOfAssignedParkingSpaces;
    protected ExtensionType assignedParkingSpacesExtension;

    /**
     * Gets the value of the numberOfAssignedParkingSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfAssignedParkingSpaces() {
        return numberOfAssignedParkingSpaces;
    }

    /**
     * Sets the value of the numberOfAssignedParkingSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfAssignedParkingSpaces(BigInteger value) {
        this.numberOfAssignedParkingSpaces = value;
    }

    /**
     * Gets the value of the descriptionOfAssignedParkingSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionOfAssignedParkingSpaces }
     *     
     */
    public DescriptionOfAssignedParkingSpaces getDescriptionOfAssignedParkingSpaces() {
        return descriptionOfAssignedParkingSpaces;
    }

    /**
     * Sets the value of the descriptionOfAssignedParkingSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionOfAssignedParkingSpaces }
     *     
     */
    public void setDescriptionOfAssignedParkingSpaces(DescriptionOfAssignedParkingSpaces value) {
        this.descriptionOfAssignedParkingSpaces = value;
    }

    /**
     * Gets the value of the assignedParkingSpacesExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getAssignedParkingSpacesExtension() {
        return assignedParkingSpacesExtension;
    }

    /**
     * Sets the value of the assignedParkingSpacesExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setAssignedParkingSpacesExtension(ExtensionType value) {
        this.assignedParkingSpacesExtension = value;
    }

}
