//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specification of the type of day.
 * 
 * <p>Java class for DayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DayType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="generalDayType" type="{http://datex2.eu/schema/2/2_0}GeneralDayTypeEnum" minOccurs="0"/>
 *         &lt;element name="publicHoliday" type="{http://datex2.eu/schema/2/2_0}PublicHoliday" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dayTypeExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DayType", propOrder = {
    "generalDayType",
    "publicHoliday",
    "dayTypeExtension"
})
public class DayType {

    protected GeneralDayTypeEnum generalDayType;
    protected List<PublicHoliday> publicHoliday;
    protected ExtensionType dayTypeExtension;

    /**
     * Gets the value of the generalDayType property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralDayTypeEnum }
     *     
     */
    public GeneralDayTypeEnum getGeneralDayType() {
        return generalDayType;
    }

    /**
     * Sets the value of the generalDayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralDayTypeEnum }
     *     
     */
    public void setGeneralDayType(GeneralDayTypeEnum value) {
        this.generalDayType = value;
    }

    /**
     * Gets the value of the publicHoliday property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicHoliday property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicHoliday().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicHoliday }
     * 
     * 
     */
    public List<PublicHoliday> getPublicHoliday() {
        if (publicHoliday == null) {
            publicHoliday = new ArrayList<PublicHoliday>();
        }
        return this.publicHoliday;
    }

    /**
     * Gets the value of the dayTypeExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getDayTypeExtension() {
        return dayTypeExtension;
    }

    /**
     * Sets the value of the dayTypeExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setDayTypeExtension(ExtensionType value) {
        this.dayTypeExtension = value;
    }

}
