//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Description of the type of assigned parking spaces.
 * 
 * <p>Java class for DescriptionOfAssignedParkingSpaces complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptionOfAssignedParkingSpaces">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parkingDuration" type="{http://datex2.eu/schema/2/2_0}ParkingDurationEnum" minOccurs="0"/>
 *         &lt;element name="personTypeForWhichSpacesAssigned" type="{http://datex2.eu/schema/2/2_0}ParkingPersonTypeEnum" minOccurs="0"/>
 *         &lt;element name="characteristicsOfVehiclesForWhichSpacesAssigned" type="{http://datex2.eu/schema/2/2_0}VehicleCharacteristics" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="descriptionOfAssignedParkingSpacesExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptionOfAssignedParkingSpaces", propOrder = {
    "parkingDuration",
    "personTypeForWhichSpacesAssigned",
    "characteristicsOfVehiclesForWhichSpacesAssigned",
    "descriptionOfAssignedParkingSpacesExtension"
})
public class DescriptionOfAssignedParkingSpaces {

    protected ParkingDurationEnum parkingDuration;
    protected ParkingPersonTypeEnum personTypeForWhichSpacesAssigned;
    protected List<VehicleCharacteristics> characteristicsOfVehiclesForWhichSpacesAssigned;
    protected ExtensionType descriptionOfAssignedParkingSpacesExtension;

    /**
     * Gets the value of the parkingDuration property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingDurationEnum }
     *     
     */
    public ParkingDurationEnum getParkingDuration() {
        return parkingDuration;
    }

    /**
     * Sets the value of the parkingDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingDurationEnum }
     *     
     */
    public void setParkingDuration(ParkingDurationEnum value) {
        this.parkingDuration = value;
    }

    /**
     * Gets the value of the personTypeForWhichSpacesAssigned property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingPersonTypeEnum }
     *     
     */
    public ParkingPersonTypeEnum getPersonTypeForWhichSpacesAssigned() {
        return personTypeForWhichSpacesAssigned;
    }

    /**
     * Sets the value of the personTypeForWhichSpacesAssigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingPersonTypeEnum }
     *     
     */
    public void setPersonTypeForWhichSpacesAssigned(ParkingPersonTypeEnum value) {
        this.personTypeForWhichSpacesAssigned = value;
    }

    /**
     * Gets the value of the characteristicsOfVehiclesForWhichSpacesAssigned property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characteristicsOfVehiclesForWhichSpacesAssigned property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacteristicsOfVehiclesForWhichSpacesAssigned().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleCharacteristics }
     * 
     * 
     */
    public List<VehicleCharacteristics> getCharacteristicsOfVehiclesForWhichSpacesAssigned() {
        if (characteristicsOfVehiclesForWhichSpacesAssigned == null) {
            characteristicsOfVehiclesForWhichSpacesAssigned = new ArrayList<VehicleCharacteristics>();
        }
        return this.characteristicsOfVehiclesForWhichSpacesAssigned;
    }

    /**
     * Gets the value of the descriptionOfAssignedParkingSpacesExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getDescriptionOfAssignedParkingSpacesExtension() {
        return descriptionOfAssignedParkingSpacesExtension;
    }

    /**
     * Sets the value of the descriptionOfAssignedParkingSpacesExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setDescriptionOfAssignedParkingSpacesExtension(ExtensionType value) {
        this.descriptionOfAssignedParkingSpacesExtension = value;
    }

}
