//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.datex2.schema._2._2_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _D2LogicalModel_QNAME = new QName("http://datex2.eu/schema/2/2_0", "d2LogicalModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.datex2.schema._2._2_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MultilingualString }
     * 
     */
    public MultilingualString createMultilingualString() {
        return new MultilingualString();
    }

    /**
     * Create an instance of {@link D2LogicalModel }
     * 
     */
    public D2LogicalModel createD2LogicalModel() {
        return new D2LogicalModel();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link VehicleCharacteristics }
     * 
     */
    public VehicleCharacteristics createVehicleCharacteristics() {
        return new VehicleCharacteristics();
    }

    /**
     * Create an instance of {@link PublicHoliday }
     * 
     */
    public PublicHoliday createPublicHoliday() {
        return new PublicHoliday();
    }

    /**
     * Create an instance of {@link GenericPublication }
     * 
     */
    public GenericPublication createGenericPublication() {
        return new GenericPublication();
    }

    /**
     * Create an instance of {@link OpenlrLocationReferencePoint }
     * 
     */
    public OpenlrLocationReferencePoint createOpenlrLocationReferencePoint() {
        return new OpenlrLocationReferencePoint();
    }

    /**
     * Create an instance of {@link PointExtensionType }
     * 
     */
    public PointExtensionType createPointExtensionType() {
        return new PointExtensionType();
    }

    /**
     * Create an instance of {@link LinearElementByCode }
     * 
     */
    public LinearElementByCode createLinearElementByCode() {
        return new LinearElementByCode();
    }

    /**
     * Create an instance of {@link PointByCoordinates }
     * 
     */
    public PointByCoordinates createPointByCoordinates() {
        return new PointByCoordinates();
    }

    /**
     * Create an instance of {@link MultilingualStringValue }
     * 
     */
    public MultilingualStringValue createMultilingualStringValue() {
        return new MultilingualStringValue();
    }

    /**
     * Create an instance of {@link ParkingFacilityTablePublication }
     * 
     */
    public ParkingFacilityTablePublication createParkingFacilityTablePublication() {
        return new ParkingFacilityTablePublication();
    }

    /**
     * Create an instance of {@link OffsetDistance }
     * 
     */
    public OffsetDistance createOffsetDistance() {
        return new OffsetDistance();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link ExternalReferencing }
     * 
     */
    public ExternalReferencing createExternalReferencing() {
        return new ExternalReferencing();
    }

    /**
     * Create an instance of {@link ParkingFacility }
     * 
     */
    public ParkingFacility createParkingFacility() {
        return new ParkingFacility();
    }

    /**
     * Create an instance of {@link VmsUnitRecordVersionedReference }
     * 
     */
    public VmsUnitRecordVersionedReference createVmsUnitRecordVersionedReference() {
        return new VmsUnitRecordVersionedReference();
    }

    /**
     * Create an instance of {@link PolygonAreaIndexPointCoordinates }
     * 
     */
    public PolygonAreaIndexPointCoordinates createPolygonAreaIndexPointCoordinates() {
        return new PolygonAreaIndexPointCoordinates();
    }

    /**
     * Create an instance of {@link AreaExtended }
     * 
     */
    public AreaExtended createAreaExtended() {
        return new AreaExtended();
    }

    /**
     * Create an instance of {@link IntermediatePointOnLinearElement }
     * 
     */
    public IntermediatePointOnLinearElement createIntermediatePointOnLinearElement() {
        return new IntermediatePointOnLinearElement();
    }

    /**
     * Create an instance of {@link PointCoordinates }
     * 
     */
    public PointCoordinates createPointCoordinates() {
        return new PointCoordinates();
    }

    /**
     * Create an instance of {@link ParkingFacilityTable }
     * 
     */
    public ParkingFacilityTable createParkingFacilityTable() {
        return new ParkingFacilityTable();
    }

    /**
     * Create an instance of {@link OpenlrGeoCoordinate }
     * 
     */
    public OpenlrGeoCoordinate createOpenlrGeoCoordinate() {
        return new OpenlrGeoCoordinate();
    }

    /**
     * Create an instance of {@link AlertCMethod4Point }
     * 
     */
    public AlertCMethod4Point createAlertCMethod4Point() {
        return new AlertCMethod4Point();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link DescriptionOfAssignedParkingSpaces }
     * 
     */
    public DescriptionOfAssignedParkingSpaces createDescriptionOfAssignedParkingSpaces() {
        return new DescriptionOfAssignedParkingSpaces();
    }

    /**
     * Create an instance of {@link OpenlrExtendedPoint }
     * 
     */
    public OpenlrExtendedPoint createOpenlrExtendedPoint() {
        return new OpenlrExtendedPoint();
    }

    /**
     * Create an instance of {@link DayType }
     * 
     */
    public DayType createDayType() {
        return new DayType();
    }

    /**
     * Create an instance of {@link InternationalIdentifier }
     * 
     */
    public InternationalIdentifier createInternationalIdentifier() {
        return new InternationalIdentifier();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link AreaExtensionType }
     * 
     */
    public AreaExtensionType createAreaExtensionType() {
        return new AreaExtensionType();
    }

    /**
     * Create an instance of {@link LinearElement }
     * 
     */
    public LinearElement createLinearElement() {
        return new LinearElement();
    }

    /**
     * Create an instance of {@link GenericPublicationExtensionType }
     * 
     */
    public GenericPublicationExtensionType createGenericPublicationExtensionType() {
        return new GenericPublicationExtensionType();
    }

    /**
     * Create an instance of {@link OpenlrPointLocationReference }
     * 
     */
    public OpenlrPointLocationReference createOpenlrPointLocationReference() {
        return new OpenlrPointLocationReference();
    }

    /**
     * Create an instance of {@link OpenlrPoiWithAccessPoint }
     * 
     */
    public OpenlrPoiWithAccessPoint createOpenlrPoiWithAccessPoint() {
        return new OpenlrPoiWithAccessPoint();
    }

    /**
     * Create an instance of {@link OpeningTimes }
     * 
     */
    public OpeningTimes createOpeningTimes() {
        return new OpeningTimes();
    }

    /**
     * Create an instance of {@link PolygonArea }
     * 
     */
    public PolygonArea createPolygonArea() {
        return new PolygonArea();
    }

    /**
     * Create an instance of {@link Exchange }
     * 
     */
    public Exchange createExchange() {
        return new Exchange();
    }

    /**
     * Create an instance of {@link VersionedReference }
     * 
     */
    public VersionedReference createVersionedReference() {
        return new VersionedReference();
    }

    /**
     * Create an instance of {@link AlertCMethod4PrimaryPointLocation }
     * 
     */
    public AlertCMethod4PrimaryPointLocation createAlertCMethod4PrimaryPointLocation() {
        return new AlertCMethod4PrimaryPointLocation();
    }

    /**
     * Create an instance of {@link AlertCDirection }
     * 
     */
    public AlertCDirection createAlertCDirection() {
        return new AlertCDirection();
    }

    /**
     * Create an instance of {@link PointAlongLinearElement }
     * 
     */
    public PointAlongLinearElement createPointAlongLinearElement() {
        return new PointAlongLinearElement();
    }

    /**
     * Create an instance of {@link HeaderInformation }
     * 
     */
    public HeaderInformation createHeaderInformation() {
        return new HeaderInformation();
    }

    /**
     * Create an instance of {@link ParkingFacilityIndexAssignedParkingSpaces }
     * 
     */
    public ParkingFacilityIndexAssignedParkingSpaces createParkingFacilityIndexAssignedParkingSpaces() {
        return new ParkingFacilityIndexAssignedParkingSpaces();
    }

    /**
     * Create an instance of {@link LinearElementByPoints }
     * 
     */
    public LinearElementByPoints createLinearElementByPoints() {
        return new LinearElementByPoints();
    }

    /**
     * Create an instance of {@link OpenlrLastLocationReferencePoint }
     * 
     */
    public OpenlrLastLocationReferencePoint createOpenlrLastLocationReferencePoint() {
        return new OpenlrLastLocationReferencePoint();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link OpenlrLineAttributes }
     * 
     */
    public OpenlrLineAttributes createOpenlrLineAttributes() {
        return new OpenlrLineAttributes();
    }

    /**
     * Create an instance of {@link OpenlrPointAlongLine }
     * 
     */
    public OpenlrPointAlongLine createOpenlrPointAlongLine() {
        return new OpenlrPointAlongLine();
    }

    /**
     * Create an instance of {@link DistanceFromLinearElementStart }
     * 
     */
    public DistanceFromLinearElementStart createDistanceFromLinearElementStart() {
        return new DistanceFromLinearElementStart();
    }

    /**
     * Create an instance of {@link Referent }
     * 
     */
    public Referent createReferent() {
        return new Referent();
    }

    /**
     * Create an instance of {@link HeightCharacteristic }
     * 
     */
    public HeightCharacteristic createHeightCharacteristic() {
        return new HeightCharacteristic();
    }

    /**
     * Create an instance of {@link ParkingArea }
     * 
     */
    public ParkingArea createParkingArea() {
        return new ParkingArea();
    }

    /**
     * Create an instance of {@link AlertCLocation }
     * 
     */
    public AlertCLocation createAlertCLocation() {
        return new AlertCLocation();
    }

    /**
     * Create an instance of {@link AssignedParkingSpaces }
     * 
     */
    public AssignedParkingSpaces createAssignedParkingSpaces() {
        return new AssignedParkingSpaces();
    }

    /**
     * Create an instance of {@link MultilingualString.Values }
     * 
     */
    public MultilingualString.Values createMultilingualStringValues() {
        return new MultilingualString.Values();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link D2LogicalModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://datex2.eu/schema/2/2_0", name = "d2LogicalModel")
    public JAXBElement<D2LogicalModel> createD2LogicalModel(D2LogicalModel value) {
        return new JAXBElement<D2LogicalModel>(_D2LogicalModel_QNAME, D2LogicalModel.class, null, value);
    }

}
