//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Extension class for OpenLR point. 
 * 
 * <p>Java class for OpenlrExtendedPoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpenlrExtendedPoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="openlrPointLocationReference" type="{http://datex2.eu/schema/2/2_0}OpenlrPointLocationReference"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpenlrExtendedPoint", propOrder = {
    "openlrPointLocationReference"
})
public class OpenlrExtendedPoint {

    @XmlElement(required = true)
    protected OpenlrPointLocationReference openlrPointLocationReference;

    /**
     * Gets the value of the openlrPointLocationReference property.
     * 
     * @return
     *     possible object is
     *     {@link OpenlrPointLocationReference }
     *     
     */
    public OpenlrPointLocationReference getOpenlrPointLocationReference() {
        return openlrPointLocationReference;
    }

    /**
     * Sets the value of the openlrPointLocationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenlrPointLocationReference }
     *     
     */
    public void setOpenlrPointLocationReference(OpenlrPointLocationReference value) {
        this.openlrPointLocationReference = value;
    }

}
