//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datex2.eu/schema/2/2_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.datex2.schema._2._2_0;
