//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParkingDurationEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParkingDurationEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pickUpDropOff"/>
 *     &lt;enumeration value="shortTerm"/>
 *     &lt;enumeration value="shortTerm24hours"/>
 *     &lt;enumeration value="shortTerm48hours"/>
 *     &lt;enumeration value="shortTerm72hours"/>
 *     &lt;enumeration value="shortTerm96hours"/>
 *     &lt;enumeration value="longTerm"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ParkingDurationEnum")
@XmlEnum
public enum ParkingDurationEnum {


    /**
     * Very short duration parking normally of up to 20 minutes assigned for pick-ups and drop-offs.
     * 
     */
    @XmlEnumValue("pickUpDropOff")
    PICK_UP_DROP_OFF("pickUpDropOff"),

    /**
     * Short term parking without indication of max-duration
     * 
     */
    @XmlEnumValue("shortTerm")
    SHORT_TERM("shortTerm"),

    /**
     * Short term parking up to 24 hours.
     * 
     */
    @XmlEnumValue("shortTerm24hours")
    SHORT_TERM_24_HOURS("shortTerm24hours"),

    /**
     * Short term parking up to 48 hours.
     * 
     */
    @XmlEnumValue("shortTerm48hours")
    SHORT_TERM_48_HOURS("shortTerm48hours"),

    /**
     * Short term parking up to 72 hours.
     * 
     */
    @XmlEnumValue("shortTerm72hours")
    SHORT_TERM_72_HOURS("shortTerm72hours"),

    /**
     * Short term parking up to 96 hours.
     * 
     */
    @XmlEnumValue("shortTerm96hours")
    SHORT_TERM_96_HOURS("shortTerm96hours"),

    /**
     * Long term parking in excess of any specified short term parking.
     * 
     */
    @XmlEnumValue("longTerm")
    LONG_TERM("longTerm");
    private final String value;

    ParkingDurationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParkingDurationEnum fromValue(String v) {
        for (ParkingDurationEnum c: ParkingDurationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
