//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of parking facilities relating to a specific area, where each entry identifies static characteristics relating to an individual parking facility.
 * 
 * <p>Java class for ParkingArea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParkingArea">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parkingAreaName" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/>
 *         &lt;element name="totalParkingCapacity" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="totalParkingCapacityLongTerm" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="totalParkingCapacityShortTerm" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="area" type="{http://datex2.eu/schema/2/2_0}Area" minOccurs="0"/>
 *         &lt;element name="parkingFacility" type="{http://datex2.eu/schema/2/2_0}ParkingFacility" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="parkingAreaExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParkingArea", propOrder = {
    "parkingAreaName",
    "totalParkingCapacity",
    "totalParkingCapacityLongTerm",
    "totalParkingCapacityShortTerm",
    "area",
    "parkingFacility",
    "parkingAreaExtension"
})
public class ParkingArea {

    protected MultilingualString parkingAreaName;
    protected BigInteger totalParkingCapacity;
    protected BigInteger totalParkingCapacityLongTerm;
    protected BigInteger totalParkingCapacityShortTerm;
    protected Area area;
    protected List<ParkingFacility> parkingFacility;
    protected ExtensionType parkingAreaExtension;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the parkingAreaName property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getParkingAreaName() {
        return parkingAreaName;
    }

    /**
     * Sets the value of the parkingAreaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setParkingAreaName(MultilingualString value) {
        this.parkingAreaName = value;
    }

    /**
     * Gets the value of the totalParkingCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalParkingCapacity() {
        return totalParkingCapacity;
    }

    /**
     * Sets the value of the totalParkingCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalParkingCapacity(BigInteger value) {
        this.totalParkingCapacity = value;
    }

    /**
     * Gets the value of the totalParkingCapacityLongTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalParkingCapacityLongTerm() {
        return totalParkingCapacityLongTerm;
    }

    /**
     * Sets the value of the totalParkingCapacityLongTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalParkingCapacityLongTerm(BigInteger value) {
        this.totalParkingCapacityLongTerm = value;
    }

    /**
     * Gets the value of the totalParkingCapacityShortTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalParkingCapacityShortTerm() {
        return totalParkingCapacityShortTerm;
    }

    /**
     * Sets the value of the totalParkingCapacityShortTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalParkingCapacityShortTerm(BigInteger value) {
        this.totalParkingCapacityShortTerm = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setArea(Area value) {
        this.area = value;
    }

    /**
     * Gets the value of the parkingFacility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parkingFacility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParkingFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParkingFacility }
     * 
     * 
     */
    public List<ParkingFacility> getParkingFacility() {
        if (parkingFacility == null) {
            parkingFacility = new ArrayList<ParkingFacility>();
        }
        return this.parkingFacility;
    }

    /**
     * Gets the value of the parkingAreaExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getParkingAreaExtension() {
        return parkingAreaExtension;
    }

    /**
     * Sets the value of the parkingAreaExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setParkingAreaExtension(ExtensionType value) {
        this.parkingAreaExtension = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
