//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A record containing the static details of a specific parking facility which may be a park house, a parking area or zone with controlled access and with defined parking capacity.
 * 
 * <p>Java class for ParkingFacility complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParkingFacility">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parkingFacilityDescription" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/>
 *         &lt;element name="parkingFacilityLayout" type="{http://datex2.eu/schema/2/2_0}ParkingFacilityLayoutEnum" minOccurs="0"/>
 *         &lt;element name="parkingFacilityName" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/>
 *         &lt;element name="parkingFacilityRecordVersionTime" type="{http://datex2.eu/schema/2/2_0}DateTime"/>
 *         &lt;element name="totalParkingCapacityLongTerm" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="totalParkingCapacityShortTerm" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="totalParkingCapacity" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="vmsUnitUsedToManageParkingFacility" type="{http://datex2.eu/schema/2/2_0}_VmsUnitRecordVersionedReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="openingTimes" type="{http://datex2.eu/schema/2/2_0}OpeningTimes" minOccurs="0"/>
 *         &lt;element name="facilityLocation" type="{http://datex2.eu/schema/2/2_0}Location"/>
 *         &lt;element name="entranceLocation" type="{http://datex2.eu/schema/2/2_0}Point" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="exitLocation" type="{http://datex2.eu/schema/2/2_0}Point" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="characteristicsOfPermittedVehicles" type="{http://datex2.eu/schema/2/2_0}VehicleCharacteristics" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="owner" type="{http://datex2.eu/schema/2/2_0}Contact" minOccurs="0"/>
 *         &lt;element name="assignedParkingSpaces" type="{http://datex2.eu/schema/2/2_0}_ParkingFacilityIndexAssignedParkingSpaces" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="parkingFacilityExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParkingFacility", propOrder = {
    "parkingFacilityDescription",
    "parkingFacilityLayout",
    "parkingFacilityName",
    "parkingFacilityRecordVersionTime",
    "totalParkingCapacityLongTerm",
    "totalParkingCapacityShortTerm",
    "totalParkingCapacity",
    "vmsUnitUsedToManageParkingFacility",
    "openingTimes",
    "facilityLocation",
    "entranceLocation",
    "exitLocation",
    "characteristicsOfPermittedVehicles",
    "owner",
    "assignedParkingSpaces",
    "parkingFacilityExtension"
})
public class ParkingFacility {

    protected String parkingFacilityDescription;
    protected ParkingFacilityLayoutEnum parkingFacilityLayout;
    protected MultilingualString parkingFacilityName;
    @XmlElement(required = true)
    protected XMLGregorianCalendar parkingFacilityRecordVersionTime;
    protected BigInteger totalParkingCapacityLongTerm;
    protected BigInteger totalParkingCapacityShortTerm;
    protected BigInteger totalParkingCapacity;
    protected List<VmsUnitRecordVersionedReference> vmsUnitUsedToManageParkingFacility;
    protected OpeningTimes openingTimes;
    @XmlElement(required = true)
    protected Location facilityLocation;
    protected List<Point> entranceLocation;
    protected List<Point> exitLocation;
    protected List<VehicleCharacteristics> characteristicsOfPermittedVehicles;
    protected Contact owner;
    protected List<ParkingFacilityIndexAssignedParkingSpaces> assignedParkingSpaces;
    protected ExtensionType parkingFacilityExtension;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the parkingFacilityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParkingFacilityDescription() {
        return parkingFacilityDescription;
    }

    /**
     * Sets the value of the parkingFacilityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParkingFacilityDescription(String value) {
        this.parkingFacilityDescription = value;
    }

    /**
     * Gets the value of the parkingFacilityLayout property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingFacilityLayoutEnum }
     *     
     */
    public ParkingFacilityLayoutEnum getParkingFacilityLayout() {
        return parkingFacilityLayout;
    }

    /**
     * Sets the value of the parkingFacilityLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingFacilityLayoutEnum }
     *     
     */
    public void setParkingFacilityLayout(ParkingFacilityLayoutEnum value) {
        this.parkingFacilityLayout = value;
    }

    /**
     * Gets the value of the parkingFacilityName property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getParkingFacilityName() {
        return parkingFacilityName;
    }

    /**
     * Sets the value of the parkingFacilityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setParkingFacilityName(MultilingualString value) {
        this.parkingFacilityName = value;
    }

    /**
     * Gets the value of the parkingFacilityRecordVersionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getParkingFacilityRecordVersionTime() {
        return parkingFacilityRecordVersionTime;
    }

    /**
     * Sets the value of the parkingFacilityRecordVersionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setParkingFacilityRecordVersionTime(XMLGregorianCalendar value) {
        this.parkingFacilityRecordVersionTime = value;
    }

    /**
     * Gets the value of the totalParkingCapacityLongTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalParkingCapacityLongTerm() {
        return totalParkingCapacityLongTerm;
    }

    /**
     * Sets the value of the totalParkingCapacityLongTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalParkingCapacityLongTerm(BigInteger value) {
        this.totalParkingCapacityLongTerm = value;
    }

    /**
     * Gets the value of the totalParkingCapacityShortTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalParkingCapacityShortTerm() {
        return totalParkingCapacityShortTerm;
    }

    /**
     * Sets the value of the totalParkingCapacityShortTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalParkingCapacityShortTerm(BigInteger value) {
        this.totalParkingCapacityShortTerm = value;
    }

    /**
     * Gets the value of the totalParkingCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalParkingCapacity() {
        return totalParkingCapacity;
    }

    /**
     * Sets the value of the totalParkingCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalParkingCapacity(BigInteger value) {
        this.totalParkingCapacity = value;
    }

    /**
     * Gets the value of the vmsUnitUsedToManageParkingFacility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vmsUnitUsedToManageParkingFacility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVmsUnitUsedToManageParkingFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VmsUnitRecordVersionedReference }
     * 
     * 
     */
    public List<VmsUnitRecordVersionedReference> getVmsUnitUsedToManageParkingFacility() {
        if (vmsUnitUsedToManageParkingFacility == null) {
            vmsUnitUsedToManageParkingFacility = new ArrayList<VmsUnitRecordVersionedReference>();
        }
        return this.vmsUnitUsedToManageParkingFacility;
    }

    /**
     * Gets the value of the openingTimes property.
     * 
     * @return
     *     possible object is
     *     {@link OpeningTimes }
     *     
     */
    public OpeningTimes getOpeningTimes() {
        return openingTimes;
    }

    /**
     * Sets the value of the openingTimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpeningTimes }
     *     
     */
    public void setOpeningTimes(OpeningTimes value) {
        this.openingTimes = value;
    }

    /**
     * Gets the value of the facilityLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getFacilityLocation() {
        return facilityLocation;
    }

    /**
     * Sets the value of the facilityLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setFacilityLocation(Location value) {
        this.facilityLocation = value;
    }

    /**
     * Gets the value of the entranceLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entranceLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntranceLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getEntranceLocation() {
        if (entranceLocation == null) {
            entranceLocation = new ArrayList<Point>();
        }
        return this.entranceLocation;
    }

    /**
     * Gets the value of the exitLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exitLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExitLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getExitLocation() {
        if (exitLocation == null) {
            exitLocation = new ArrayList<Point>();
        }
        return this.exitLocation;
    }

    /**
     * Gets the value of the characteristicsOfPermittedVehicles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characteristicsOfPermittedVehicles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacteristicsOfPermittedVehicles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleCharacteristics }
     * 
     * 
     */
    public List<VehicleCharacteristics> getCharacteristicsOfPermittedVehicles() {
        if (characteristicsOfPermittedVehicles == null) {
            characteristicsOfPermittedVehicles = new ArrayList<VehicleCharacteristics>();
        }
        return this.characteristicsOfPermittedVehicles;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     */
    public void setOwner(Contact value) {
        this.owner = value;
    }

    /**
     * Gets the value of the assignedParkingSpaces property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignedParkingSpaces property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignedParkingSpaces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParkingFacilityIndexAssignedParkingSpaces }
     * 
     * 
     */
    public List<ParkingFacilityIndexAssignedParkingSpaces> getAssignedParkingSpaces() {
        if (assignedParkingSpaces == null) {
            assignedParkingSpaces = new ArrayList<ParkingFacilityIndexAssignedParkingSpaces>();
        }
        return this.assignedParkingSpaces;
    }

    /**
     * Gets the value of the parkingFacilityExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getParkingFacilityExtension() {
        return parkingFacilityExtension;
    }

    /**
     * Sets the value of the parkingFacilityExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setParkingFacilityExtension(ExtensionType value) {
        this.parkingFacilityExtension = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
