//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 02:48:15 PM CET 
//


package eu.datex2.schema._2._2_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specification of the public holiday type in a specific country or region.
 * 
 * <p>Java class for PublicHoliday complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicHoliday">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" type="{http://datex2.eu/schema/2/2_0}CountryEnum"/>
 *         &lt;element name="countrySubdivision" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/>
 *         &lt;element name="region" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/>
 *         &lt;element name="publicHolidayType" type="{http://datex2.eu/schema/2/2_0}PublicHolidayTypeEnum"/>
 *         &lt;element name="publicHolidayExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicHoliday", propOrder = {
    "country",
    "countrySubdivision",
    "region",
    "publicHolidayType",
    "publicHolidayExtension"
})
public class PublicHoliday {

    @XmlElement(required = true)
    protected CountryEnum country;
    protected String countrySubdivision;
    protected String region;
    @XmlElement(required = true)
    protected PublicHolidayTypeEnum publicHolidayType;
    protected ExtensionType publicHolidayExtension;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CountryEnum }
     *     
     */
    public CountryEnum getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryEnum }
     *     
     */
    public void setCountry(CountryEnum value) {
        this.country = value;
    }

    /**
     * Gets the value of the countrySubdivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountrySubdivision() {
        return countrySubdivision;
    }

    /**
     * Sets the value of the countrySubdivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountrySubdivision(String value) {
        this.countrySubdivision = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the publicHolidayType property.
     * 
     * @return
     *     possible object is
     *     {@link PublicHolidayTypeEnum }
     *     
     */
    public PublicHolidayTypeEnum getPublicHolidayType() {
        return publicHolidayType;
    }

    /**
     * Sets the value of the publicHolidayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicHolidayTypeEnum }
     *     
     */
    public void setPublicHolidayType(PublicHolidayTypeEnum value) {
        this.publicHolidayType = value;
    }

    /**
     * Gets the value of the publicHolidayExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getPublicHolidayExtension() {
        return publicHolidayExtension;
    }

    /**
     * Sets the value of the publicHolidayExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setPublicHolidayExtension(ExtensionType value) {
        this.publicHolidayExtension = value;
    }

}
